---
- name: "Download {{ app_name }}-{{ pkg_name }}.tar.gz file and untar the package under {{ software_download_local_dir }}"
  unarchive:
    src: "{{ app_source_url }}/{{ pkg_name }}/{{ app_name }}-{{ pkg_name }}.tar.gz"
    dest: "{{ software_download_local_dir }}"
    mode: "{{ file_permission }}"
    remote_src: yes
...