---
- name: Include task for RollBack
  include_tasks: rollback.yml
#Tested Successfully
#- name: Include task for Software_download
#  include_tasks: software_download.yml

- name: Include task for Pre-validation
  include_tasks: application_valid.yml

- name: Include task for installing package
  include_tasks: application_install.yml
  when: rollback_flag is defined and rollback_flag == 'false' and (not version_result.stat.exists or (version_result.stat.exists and pkg_name not in version_result.stat.lnk_target))

- name: Include task to Rollback and start application
  include_tasks: application_rollback.yml
  when: rollback_flag is defined and rollback_flag == 'true'

- name: Start application
  include_tasks: application_startup.yml
  when: rollback_flag is defined and rollback_flag == 'false'
  #delegate_to: "{{item}}"
  with_items: "{{ ansible_play_hosts_all }}"
  loop_control:
        loop_var: delegate_host
  run_once: true

- name: Include the task for post validation
  include_tasks: general_post_validation.yml
...