---
- name: Include task for RollBack
  include_tasks: rollback.yml

- name: Include task for Software_download
  include_tasks: software_download.yml

- name: Include task for Pre-validation
  include_tasks: application_valid.yml

- name: Include task for installing package
  include_tasks: application_install.yml

- name: Include task for installing package
  include_tasks: application_rollback.yml

- name: Include the task for post validation
  include_tasks: general_post_validation.yml
...